### ISSUE TITLE
Property property of MemberExpression expected node to be of a type [\"Identifier\"] but instead got null

### ISSUE THREAD

**Issue by sibelius** [bvic23/babel-plugin-functional-hmr#4]
```jsx
import { Text as RNText, StyleSheet } from 'react-native';

export const Text = ({ style, children, capitalized, ...props }: Object) =>
  <RNText style={[styles.font, style]} {...props}>
    {capitalized ? capitalizeFirstLetter(children) : children}
  </RNText>;
```

**Comment by bvic23** [comment]
Hey @sibelius! Thanks for reporting, I will fix this soon.

**Comment by bvic23** [comment]
@sibelius Could you provide some more context?

**Comment by kylealwyn** [comment]
Getting the same thing. I think I've narrowed it down to the `...props`. Seems like it's barfing on the "rest" syntax

**Comment by bvic23** [comment]
@kylealwyn @sibelius I'm not a JS expert but it seems like invalid syntax to me: AFAIK you can't use spread syntax in a destruct expression (`props`). Valid syntax would be:

```js
export const Text = ({ style, children, capitalized, props }: Object) =>
  <RNText style={[styles.font, style]} {...props}>
    {capitalized ? capitalizeFirstLetter(children) : children}
  </RNText>;
```

**Comment by sibelius** [comment]
In fact, you can

**Comment by bvic23** [comment]
Could you explain me how? And how can destruct the already destructed `props` in the method body?

**Comment by bvic23** [comment]
@sibelius seems like you are way more experienced than me please help me and send a PR with the fix

**Comment by kylealwyn** [comment]
@bvic23 The syntax and method is called "rest" parameters: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/rest_parameters

It works the same for arrays as it does with objects. when destructuring, it effectively assigns the rest of the object or array into the variable. take for example:

```js
const obj = {
   a: 1,
   b: 2,
   c: 3,
};

const { a, ...rest } =  obj;
// a is 1 here, rest is { b: 2, c: 3 }
```

This method works nicely with React because you may only want to pluck a couple properties out of the props arg and pass the rest down to the native view.

I have no experience with babel transforms and it's AST process but I'm happy to help in any way
